name: Checks

on:
  push:
    branches: [ master ]
  pull_request:
jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11" ]
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          # prerequisites
          python -m pip install --upgrade pip wheel
          python -m pip install codecov pytest pytest-cov
          # install dependencies
          pip install -e .[all]
          # show installed packages
          pip freeze
      - name: Test with pytest
        run: |
          pytest --cov --cov-report=html multipoles
      - name: Submit code coverage
        run: |          
          codecov -t ${{ secrets.CODECOV_TOKEN }}
